//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingWPF.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int idZakaz { get; set; }
        public int idMenu { get; set; }
        public int idBludo { get; set; }
        public int idNapitok { get; set; }
        public int numStol { get; set; }
        public int id_client { get; set; }
        public System.DateTime date { get; set; }
        public double Summ { get; set; }
    
        public virtual Bludo Bludo { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Napitok Napitok { get; set; }
        public virtual Users Users { get; set; }
    }
}
